import type { Metadata } from 'next';
import { Inter, Lusitana } from 'next/font/google';
import './globals.css';
import { MobileNav } from '@/components/mobile-nav';
import { MainNav } from '@/components/main-nav';

const inter = Inter({ subsets: ['latin'] });
export const lusitana = Lusitana({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} min-h-screen`}>
        <MainNav />
        {children}
      </body>
    </html>
  );
}
